name: Bug Report
description: File a bug report
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "# GitHub Issue: Bug Report Template"

  - type: input
    id: title
    attributes:
      label: Title
      description: Provide a concise and clear summary of the bug.
      placeholder: "e.g., Application crashes on selecting the 'Save' option"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detail what the bug is, where it occurs in the application, and any other important information.
      placeholder: "A detailed description of the bug..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide clear, step-by-step instructions on how to reproduce the bug.
      placeholder: |
        1. Open the application
        2. Click on the 'File' menu
        3. Select the 'Save' option
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Results
      description: Describe what should have happened if the software were functioning correctly.
      placeholder: "What you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Results
      description: Detail what actually happened when the steps were followed.
      placeholder: "What actually happened..."
    validations:
      required: true

  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Include any relevant screenshots, screen recordings, log files, or other files.
      placeholder: "Attach any relevant files here"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include details about the specific environment where the bug occurred.
      placeholder: "OS, browser version, software version, etc."
    validations:
      required: true
