name: Software Design Improvement
description: Document a potential flaw in design principles and suggest fixes
title: "[LASTNAME] Provide a short and descriptive title for the issue"
labels:
  - design
  - discussion
  - refactor
body:
  - type: markdown
    attributes:
      value: "# Design Improvement"

  - type: textarea
    id: description
    attributes:
      label: Flaw Description
      description: Describe the design principle flaw in detail.
      placeholder: "Detailed description of the observed design flaw..."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact on Project
      description: Explain the impact of this flaw on the project or user experience.
      placeholder: "How does this flaw affect the project or its users?"
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: Suggest a possible fix or improvement.
      placeholder: "Your suggestions for rectifying the design flaw..."
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Provide any examples, references, or screenshots that support your documentation.
      placeholder: "Links to examples, screenshots, etc."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or notes regarding the design flaw.
      placeholder: "Any additional information or context regarding the issue..."
    validations:
      required: false
